### ISSUE TITLE
Hi is this library usable right now?

### ISSUE THREAD

**Issue by mohsin363** [chRyNaN/emoji#1]
Hi @chRyNaN 

is this library usable right now? if yes then which version works?

Thanks

**Comment by chRyNaN** [comment]
@mohsin363 The code should be useable but it looks like I have to publish it to my repository. I will try and get that done this evening CT. Thanks for bringing this up.

**Comment by mohsin363** [comment]
@chRyNaN thanks for your reply, and what would be the version# that will work?

**Comment by chRyNaN** [comment]
The current version is `0.2.1`, I will see if I can create an updated version tonight though.

**Comment by mohsin363** [comment]
actually, I'm getting this error "Could not resolve com.chrynan.emoji:emoji-repo-map:0.2.1"

**Comment by mohsin363** [comment]
I'm getting this error:
Could not GET 'https://dl.bintray.com/chrynan/chrynan/org/jetbrains/kotlin/kotlin-annotation-processing-gradle/1.5.0/kotlin-annotation-processing-gradle-1.5.0.pom'. Received status code 502 from server: Bad Gateway

**Comment by chRyNaN** [comment]
The latest version `0.3.0 (5)` has been released: https://github.com/chRyNaN/emoji/releases/tag/0.3.0

To use this version, add the following repository to the `build.gradle(.kts)` file:

```kotlin
repositories {
    maven { url = uri("https://repo.repsy.io/mvn/chrynan/public") }
}
```

Then add the desired dependencies:

```kotlin
// Core
implementation("com.chrynan.emoji:emoji-core:0.3.0")

// Map repository implementation
implementation("com.chrynan.emoji:emoji-repo-map:0.3.0")

// SQLite repository implementation
implementation("com.chrynan.emoji:emoji-repo-sqlite:0.3.0")

// Jetpack Compose multiplatform EmojiWidget composable
implementation("com.chrynan.emoji:emoji-ui-compose:0.3.0")
```

Documentation for this release can be found [here](https://github.com/chRyNaN/emoji/blob/0.3.0/docs/index.md).

Please open another issue if you are still having problems.
